project:
  type: website
  output-dir: docs

website:
  title: "NLP Assignments"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Assignment 1"
        href: assignment_1/assignment_1.html
      - text: "Assignment 2"
        href: assignment_2/assignment_2.html

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2

exclude:
  - nlp-course-material/ 
  - "*.ipynb"            


 
